[build]
  # Comando de build
  command = "npm run build"
  
  # Diretório onde estão os arquivos built
  publish = "dist"

[build.environment]
  # Configuração para usar Node.js versão compatível
  NODE_VERSION = "18"

# Redirecionamentos para Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 